# Generated by Django 3.0.3 on 2020-05-17 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(blank=True, max_length=60, null=True)),
                ('goal_important', models.CharField(blank=True, max_length=60, null=True)),
                ('progress_1', models.CharField(blank=True, max_length=60, null=True)),
                ('progress_2', models.CharField(blank=True, max_length=60, null=True)),
                ('progress_3', models.CharField(blank=True, max_length=60, null=True)),
                ('deeper_progress_1', models.CharField(blank=True, max_length=60, null=True)),
                ('deeper_progress_2', models.CharField(blank=True, max_length=60, null=True)),
                ('deeper_progress_3', models.CharField(max_length=60, null=True)),
                ('deeper_progress_4', models.CharField(blank=True, max_length=60, null=True)),
                ('deeper_progress_5', models.CharField(blank=True, max_length=60, null=True)),
                ('deeper_progress_6', models.CharField(max_length=60, null=True)),
                ('deeper_progress_7', models.CharField(blank=True, max_length=60, null=True)),
                ('deeper_progress_8', models.CharField(blank=True, max_length=60, null=True)),
                ('deeper_progress_9', models.CharField(max_length=60, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
