# Generated by Django 3.0.3 on 2020-05-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_dream'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dream',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
