# Generated by Django 3.0.3 on 2020-04-30 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0002_auto_20200401_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deeper_progress_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deeper_progress_2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deeper_progress_3',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deeper_progress_4',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deeper_progress_5',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deeper_progress_6',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deeper_progress_7',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deeper_progress_8',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deeper_progress_9',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_important',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress_2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress_3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='user_goals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.UserProfile'),
        ),
    ]
