# Generated by Django 3.0.3 on 2020-04-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20200430_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='user_goals',
            new_name='user',
        ),
    ]
