# Generated by Django 3.0.3 on 2020-06-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
    ]
