# Generated by Django 3.0.3 on 2020-04-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20200430_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='user',
            new_name='user_goals',
        ),
    ]
