# Generated by Django 3.0.3 on 2020-06-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_remove_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
