# Generated by Django 3.0.3 on 2020-05-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20200501_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
    ]
