# Generated by Django 3.0.3 on 2020-06-16 18:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_auto_20200615_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='text',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None),
        ),
    ]
