# Generated by Django 3.0.3 on 2020-06-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
