# Generated by Django 3.0.3 on 2020-09-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
