# Generated by Django 3.0.3 on 2020-09-18 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0017_auto_20200911_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gratitude1', models.CharField(blank=True, max_length=40, null=True)),
                ('gratitude2', models.CharField(blank=True, max_length=40, null=True)),
                ('gratitude3', models.CharField(blank=True, max_length=40, null=True)),
                ('win1', models.CharField(blank=True, max_length=40, null=True)),
                ('win2', models.CharField(blank=True, max_length=40, null=True)),
                ('win3', models.CharField(blank=True, max_length=40, null=True)),
                ('favoriteThing', models.TextField(blank=True, max_length=150, null=True)),
                ('lessonsLearned', models.TextField(blank=True, max_length=150, null=True)),
                ('betterTomorrow', models.TextField(blank=True, max_length=150, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
